language: node_js
node_js:
  - 8.4.0
env:
  CODECLIMATE_REPO_TOKEN: 0a75a4b2ec78c12f6008a624f49c7f83d3b31a378b7e5aad4aae881bd428977c
before_script:
  - npm install -g codeclimate-test-reporter
after_success:
  - codeclimate < ./coverage/lcov.info  
