env:
  global:
    - CC_TEST_REPORTER_ID=0a75a4b2ec78c12f6008a624f49c7f83d3b31a378b7e5aad4aae881bd428977c
language: node_js
node_js:
  - 8.4.0
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
